title: MV Buddies Status
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: 'https://status.mvbuddies.de'
params:
  alwaysKeepBrandColor: true
  brand: '#0a0c0f'
  categories:
    - closed: true
      description: The main servers are located here.
      name: North Coast
    - name: East Coast
    - name: Uncategorized
  customTabs: []
  dateFormat: '2. January 2006 15:04'
  description: >-
    Wir überwachen ständig den Status unserer Dienstleistungen und falls es zu
    Unterbrechungen kommt, wird hier ein entsprechender Hinweis veröffentlicht.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '2. Jan — 15:04'
  systems:
    - category: North Coast
      name: Gateway
    - category: East Coast
      name: Backup Gateway
    - category: Uncategorized
      description: The guts of the application.
      name: API
    - category: Uncategorized
      description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      name: Media Proxy
  useLargeHeaderDesign: false
  useLogo: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
