title: MV Buddies Status
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: 'https://status.mvbuddies.de'
params:
  alwaysKeepBrandColor: true
  brand: '#6679a4'
  categories:
    - name: Server
    #- name: Adrian Server
    #- name: Jonas Server
    - name: Web- & Mailserver
      closed: true
    - name: Netzwerk Server
      closed: true
    - description: Some projects are located here.
      closed: true
      name: VPS
    - description: Some websites are located here.
      closed: true
      name: extern
  customTabs: []
  dateFormat: '2. January 2006 15:04'
  description: >-
    Wir überwachen ständig den Status unserer Dienstleistungen und falls es zu
    Unterbrechungen kommt, wird hier ein entsprechender Hinweis veröffentlicht.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: none
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '2. Jan — 15:04'
  systems:
    - category: Server
      name: Web- & Mailserver
    - category: Server
      name: Netzwerk Server
    - category: Server
      name: Adrian Server
    - category: Server
      name: Jonas Server
    - category: Web- & Mailserver
      description: Unter p2p.mvbuddies.de ist es möglich per Peer to Peer Verbindung Daten zu übertragen
      name: P2P FilePizza
    - category: Web- & Mailserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: MV Buddies Pad
    - category: Web- & Mailserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: Jonas URL Shortener
    - category: Web- & Mailserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: MV Buddies Files
    - category: Web- & Mailserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: MV Buddies Docs
    - category: Web- & Mailserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: Webmin
    - category: Pi Server
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: MV Buddies Pad
    - category: Netzwerk Server
      description: ''
      name: Pi-hole
    - category: Netzwerk Server
      description: ''
      name: Wireguard
    - category: extern
      description: ''
      name: Startseite
    - category: extern
      description: ''
      name: Blog
    - category: VPS
      name: MV Buddies Downloader
      description: Unter dl.mvbuddies.de ist es möglich Videos/Musik herunterzuladen
    - category: VPS
      description: ''
      name: Sharex
    - category: extern
      description: Punktzahlrechner für 11. & 12. Klasse unter rcl.mvbuddies.de
      name: Punktzahlrechner
    - category: VPS
      description: Eine minimalistische Version des Vertretungsplan unter vp.mvbuddies.de
      name: Vertretungsplan
    - category: extern
      description: Eine Sammlung über Schulinhalte
      name: Schulsammlung
    - category: extern
      description: 'Inhalte im Bereich der schulischen Mathematik, Physik & Chemie'
      name: Der Streber Blog
    - category: VPS
      description: ''
      name: MV Buddies Bot
    - category: VPS
      description: ''
      name: SupportBot Bot
    - category: VPS
      description: ''
      name: GameRoles Bot
    - category: VPS
      description: ''
      name: TTT Bot
  useLargeHeaderDesign: false
  useLogo: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
