title: MV Buddies Status
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: 'https://status.mvbuddies.de'
params:
  alwaysKeepBrandColor: true
  brand: '#0a0c0f'
  categories:
    - description: The websites are located here.
      name: Webservers
    - name: Gameservers
    - name: DiscordBot
      closed: true
  customTabs: []
  dateFormat: '2. January 2006 15:04'
  description: >-
    Wir überwachen ständig den Status unserer Dienstleistungen und falls es zu
    Unterbrechungen kommt, wird hier ein entsprechender Hinweis veröffentlicht.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '2. Jan — 15:04'
  systems:
    - description: ''
      category: Webserver
      name: Startseite
    - description: ''
      category: Webserver
      name: Blog
    - description: Unter dl.mvbuddies.de ist es möglich Videos/Musik herunterzuladen
      category: Webserver
      name: MV Buddies Downloader
    - description: Unter p2p.mvbuddies.de ist es möglich per Peer to Peer Verbindung Daten zu übertragen
      category: Webserver
      name: P2P FilePizza
    - description: ''
      category: Webserver
      name: MV Buddies Git
    - description: 'Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten'
      category: Webserver
      name: MV Buddies Pad
    - description: ''
      category: Webserver
      name: ShareX
    - description: Eine Sammlung über Schulinhalte
      category: Webserver
      name: Schulsammlung
    - description: 'Inhalte im Bereich der schulischen Mathematik, Physik & Chemie'
      category: Webserver
      name: Der Streber Blog
    - description: selbstgehosteter Gmod Server für die MV Buddies Community
      category: Gameserver
      name: Garrys Mod TTT Server
    - description: ''
      category: DiscordBot
      name: MV Buddies Bot
    - description: ''
      category: DiscordBot
      name: SupportBot Bot
    - description: ''
      category: DiscordBot
      name: GameRoles Bot
    - description: ''
      category: DiscordBot
      name: TTT Bot
  useLargeHeaderDesign: false
  useLogo: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
