title: MV Buddies Status
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: 'https://status.mvbuddies.de'
params:
  alwaysKeepBrandColor: true
  brand: '#6679a4'
  categories:
    - description: The websites are located here.
      name: Webserver
    - name: Gameserver
    - closed: true
      name: DiscordBot
  customTabs: []
  dateFormat: '2. January 2006 15:04'
  description: >-
    Wir überwachen ständig den Status unserer Dienstleistungen und falls es zu
    Unterbrechungen kommt, wird hier ein entsprechender Hinweis veröffentlicht.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: none
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '2. Jan — 15:04'
  systems:
    - category: Webserver
      description: ''
      name: Startseite
    - category: Webserver
      description: ''
      name: Blog
    - category: Webserver
      description: Unter dl.mvbuddies.de ist es möglich Videos/Musik herunterzuladen
      name: MV Buddies Downloader
    - category: Webserver
      description: >-
        Unter p2p.mvbuddies.de ist es möglich per Peer to Peer Verbindung Daten
        zu übertragen
      name: P2P FilePizza
    - category: Webserver
      description: Unter pad.mvbuddies.de ist es möglich gemeinsam via Pads zu arbeiten
      name: MV Buddies Pad
    - category: Webserver
      description: ''
      name: Sharex
    - category: Webserver
      description: 'irc.mvbuddies.de'
      name: IRC
    - category: Webserver
      description: Eine Sammlung über Schulinhalte
      name: Schulsammlung
    - category: Webserver
      description: 'Inhalte im Bereich der schulischen Mathematik, Physik & Chemie'
      name: Der Streber Blog
    - category: Gameserver
      description: selbstgehosteter Gmod Server für die MV Buddies Community
      name: Garrys Mod TTT Server
    - category: Gameserver
      description: selbstgehosteter CSGO Server für die MV Buddies Community
      name: 'CS:GO Server'
    - category: DiscordBot
      description: ''
      name: MV Buddies Bot
    - category: DiscordBot
      description: ''
      name: SupportBot Bot
    - category: DiscordBot
      description: ''
      name: GameRoles Bot
    - category: DiscordBot
      description: ''
      name: TTT Bot
  useLargeHeaderDesign: false
  useLogo: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
